In [14]:
import torch

In [15]:
t = torch.tensor([1, 2, 3], dtype=torch.float64, requires_grad=True)
t

tensor([1., 2., 3.], dtype=torch.float64, requires_grad=True)

In [16]:
print(t.dtype)
print(t.device)
print(t.shape)
print(t.requires_grad)

torch.float64
cpu
torch.Size([3])
True


In [17]:
x = torch.tensor([1, 2, 3], dtype=torch.float64)
y = torch.tensor([4, 7, 6], dtype=torch.float64)

In [18]:
print(x+y)
print(x/y)
print(x.max())
print(y.argmax())
print(y.sqrt())
print(y.sigmoid())
print(y.clamp(min=6,max=9))

tensor([5., 9., 9.], dtype=torch.float64)
tensor([0.2500, 0.2857, 0.5000], dtype=torch.float64)
tensor(3., dtype=torch.float64)
tensor(1)
tensor([2.0000, 2.6458, 2.4495], dtype=torch.float64)
tensor([0.9820, 0.9991, 0.9975], dtype=torch.float64)
tensor([6., 7., 6.], dtype=torch.float64)


In [19]:
x

tensor([1., 2., 3.], dtype=torch.float64)

In [60]:
# _ is used to do in-place operations
x.add_(1)
x.sub_(1)
x.mul_(2)
x.div_(2)
x.pow_(2)
print(x)
x.clamp_(min=0, max=1)
x

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]], dtype=torch.float64)


tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [61]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float64)

In [62]:
print(x)
# view has same memory as x
# numbers show shown according to their dim
print(x.view(1,6))
print(x)
# may not have the same memory
print(x.reshape(3,2))

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
tensor([[1., 2., 3., 4., 5., 6.]], dtype=torch.float64)
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=torch.float64)


In [63]:
# permute basically changes the order of the dimensions
print(x)
p = x.permute(1,0)
print(p)
# transpose
tr = x.t()
print(tr)
# flatten returns a 1D tensor
print(x.flatten())

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]], dtype=torch.float64)
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]], dtype=torch.float64)
tensor([1., 2., 3., 4., 5., 6.], dtype=torch.float64)


In [83]:
# removes all dim of size 1
sq = x.squeeze(1)
unsq = x.unsqueeze(-2)
print(unsq)

tensor([[[1., 2., 3.]],

        [[4., 5., 6.]]], dtype=torch.float64)


In [92]:
x

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [99]:
print(x[0,0].item())
print(x[0,:].tolist())
print(x[:,0].tolist())
print(x[:,0:2].tolist())
print(x[(x > 1) & (x < 5)].tolist())

1.0
[1.0, 2.0, 3.0]
[1.0, 4.0]
[[1.0, 2.0], [4.0, 5.0]]
[2.0, 3.0, 4.0]


In [101]:
x = torch.tensor([[1, 2], [3, 4]], dtype=torch.float64)
y = torch.tensor([[5, 6], [7, 8]], dtype=torch.float64)
print(x)
print(y)
print(torch.cat((x, y), dim=0))
print(torch.cat((x, y), dim=1))
print(torch.stack((x, y), dim=0))
print(torch.stack((x, y), dim=1))

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
tensor([[5., 6.],
        [7., 8.]], dtype=torch.float64)
tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]], dtype=torch.float64)
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]], dtype=torch.float64)
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]], dtype=torch.float64)
tensor([[[1., 2.],
         [5., 6.]],

        [[3., 4.],
         [7., 8.]]], dtype=torch.float64)


In [102]:
x = torch.tensor([[1, 2], [3, 4]], dtype=torch.float64)
y = torch.tensor([10, 20], dtype=torch.float64)
print(x)
print(y)
print(x + y)
print(x - y)
print(x * y)
print(x / y)

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
tensor([10., 20.], dtype=torch.float64)
tensor([[11., 22.],
        [13., 24.]], dtype=torch.float64)
tensor([[ -9., -18.],
        [ -7., -16.]], dtype=torch.float64)
tensor([[10., 40.],
        [30., 80.]], dtype=torch.float64)
tensor([[0.1000, 0.1000],
        [0.3000, 0.2000]], dtype=torch.float64)
