In [1]:
import torch

In [2]:
t = torch.tensor([1, 2, 3], dtype=torch.float64, requires_grad=True)
t

tensor([1., 2., 3.], dtype=torch.float64, requires_grad=True)

In [3]:
print(t.dtype)
print(t.device)
print(t.shape)
print(t.requires_grad)
x = torch.tensor([1, 2, 3], dtype=torch.float64)
y = torch.tensor([4, 7, 6], dtype=torch.float64)

torch.float64
cpu
torch.Size([3])
True


In [29]:
# initialize a tensor with a specific value
t1 = torch.ones((2,2), dtype=torch.float64)
t2 = torch.full((5,), 2, dtype=torch.float64)
t6 = torch.zeros((3,3), dtype=torch.float64)

# tensor with values from 0 to 9 in steps of 2
t3 = torch.arange(0, 10, 2, dtype=torch.float64) 
# 6 evenly spaced points between 0 and 10
t4 = torch.linspace(0, 10, 6, dtype=torch.float64)
# 4x4 identity matrix
t5 = torch.eye(4, dtype=torch.float64)
# random numbers between 0 and 1
t7 = torch.rand((2,2), dtype=torch.float64)
# random numbers from a normal distribution
t8 = torch.randn((2,2), dtype=torch.float64)
# uninitialized tensor with random values
t9 = torch.empty((2,2), dtype=torch.float64)
# tensor of zeros with the same shape as t1
t10 = torch.zeros_like(t1, dtype=torch.float64)
# random distribution with a specific mean and standard deviation
t11 = torch.normal(mean=0, std=1, size=(3,3), dtype=torch.float64)
# random integers between 0 and 10 ie [0, 10)
t12 = torch.randint(0, 10, (3,3), dtype=torch.float64)
# random permutation of integers between 0 and 10 ie [0, 10)
t13 = torch.randperm(10, dtype=torch.float64)

In [5]:
print(x+y)
print(x/y)
print(x.max())
print(y.argmax())
print(y.sqrt())
print(y.sigmoid())
print(y.clamp(min=6,max=9))

tensor([5., 9., 9.], dtype=torch.float64)
tensor([0.2500, 0.2857, 0.5000], dtype=torch.float64)
tensor(3., dtype=torch.float64)
tensor(1)
tensor([2.0000, 2.6458, 2.4495], dtype=torch.float64)
tensor([0.9820, 0.9991, 0.9975], dtype=torch.float64)
tensor([6., 7., 6.], dtype=torch.float64)


In [6]:
x

tensor([1., 2., 3.], dtype=torch.float64)

In [7]:
# _ is used to do in-place operations
x.add_(1)
x.sub_(1)
x.mul_(2)
x.div_(2)
x.pow_(2)
print(x)
x.clamp_(min=0, max=1)
x

tensor([1., 4., 9.], dtype=torch.float64)


tensor([1., 1., 1.], dtype=torch.float64)

In [34]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float64)

In [36]:
# view has same memory as x && numbers show shown according to their dim
print(x.view(1,6))
# may not have the same memory
print(x.reshape(3,2))

tensor([[1., 2., 3., 4., 5., 6.]], dtype=torch.float64)
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=torch.float64)


In [37]:
# permute basically changes the order of the dimensions
print(x.permute(1,0))
# transpose
print(x.t())
# flatten returns a 1D tensor
print(x.flatten())

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]], dtype=torch.float64)
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]], dtype=torch.float64)
tensor([1., 2., 3., 4., 5., 6.], dtype=torch.float64)


In [38]:
# removes all dim of size 1
print(x.squeeze())

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)


In [39]:
print(x)
print(x[0,0].item())
print(x[0,:].tolist())
print(x[:,0].tolist())
print(x[:,0:2].tolist())
print(x[(x > 1) & (x < 5)].tolist())

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
1.0
[1.0, 2.0, 3.0]
[1.0, 4.0]
[[1.0, 2.0], [4.0, 5.0]]
[2.0, 3.0, 4.0]


In [40]:
x = torch.tensor([[1, 2], [3, 4]], dtype=torch.float64)
y = torch.tensor([[5, 6], [7, 8]], dtype=torch.float64)
print(x)
print(y)
print(torch.cat((x, y), dim=0))
print(torch.cat((x, y), dim=1))
print(torch.stack((x, y), dim=0))
print(torch.stack((x, y), dim=1))

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
tensor([[5., 6.],
        [7., 8.]], dtype=torch.float64)
tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]], dtype=torch.float64)
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]], dtype=torch.float64)
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]], dtype=torch.float64)
tensor([[[1., 2.],
         [5., 6.]],

        [[3., 4.],
         [7., 8.]]], dtype=torch.float64)


In [41]:
x = torch.tensor([[1, 2], [3, 4]], dtype=torch.float64)
y = torch.tensor([10, 20], dtype=torch.float64)
print(x)
print(y)
print(x + y)
print(x - y)
print(x * y)
print(x / y)

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
tensor([10., 20.], dtype=torch.float64)
tensor([[11., 22.],
        [13., 24.]], dtype=torch.float64)
tensor([[ -9., -18.],
        [ -7., -16.]], dtype=torch.float64)
tensor([[10., 40.],
        [30., 80.]], dtype=torch.float64)
tensor([[0.1000, 0.1000],
        [0.3000, 0.2000]], dtype=torch.float64)
